Title: https://Maebbie.github.io
logo: /images/ravewhit.jpg
description: https://Maebbie.github.io - A simple github.io page to compile Guides and Tools I made. 
show_downloads: false
theme: jekyll-theme-slate
